// Code generated by "genenum.exe -typename=CarryingObjectType -packagename=carryingobjecttype -basedir=enum -vectortype=int"

package carryingobjecttype_vector_int

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/carryingobjecttype"
)

type CarryingObjectTypeVector_int [carryingobjecttype.CarryingObjectType_Count]int

func (es CarryingObjectTypeVector_int) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "CarryingObjectTypeVector_int[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			carryingobjecttype.CarryingObjectType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *CarryingObjectTypeVector_int) Dec(e carryingobjecttype.CarryingObjectType) {
	es[e] -= 1
}
func (es *CarryingObjectTypeVector_int) Inc(e carryingobjecttype.CarryingObjectType) {
	es[e] += 1
}
func (es *CarryingObjectTypeVector_int) Add(e carryingobjecttype.CarryingObjectType, v int) {
	es[e] += v
}
func (es *CarryingObjectTypeVector_int) SetIfGt(e carryingobjecttype.CarryingObjectType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es CarryingObjectTypeVector_int) Get(e carryingobjecttype.CarryingObjectType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es CarryingObjectTypeVector_int) Iter(fn func(i carryingobjecttype.CarryingObjectType, v int) bool) bool {
	for i, v := range es {
		if fn(carryingobjecttype.CarryingObjectType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es CarryingObjectTypeVector_int) VectorAdd(arg CarryingObjectTypeVector_int) CarryingObjectTypeVector_int {
	var rtn CarryingObjectTypeVector_int
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es CarryingObjectTypeVector_int) VectorSub(arg CarryingObjectTypeVector_int) CarryingObjectTypeVector_int {
	var rtn CarryingObjectTypeVector_int
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *CarryingObjectTypeVector_int) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>CarryingObjectType Vector int</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return carryingobjecttype.CarryingObjectType(i).String()
}

var IndexFn = template.FuncMap{
	"CarryingObjectTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{CarryingObjectTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
