// Code generated by "genenum.exe -typename=TerrainCmd -packagename=terraincmd -basedir=enum -vectortype=int"

package terraincmd_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/terraincmd"
)

type TerrainCmdVector [terraincmd.TerrainCmd_Count]int

func (es TerrainCmdVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "TerrainCmdVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			terraincmd.TerrainCmd(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *TerrainCmdVector) Dec(e terraincmd.TerrainCmd) {
	es[e] -= 1
}
func (es *TerrainCmdVector) Inc(e terraincmd.TerrainCmd) {
	es[e] += 1
}
func (es *TerrainCmdVector) Add(e terraincmd.TerrainCmd, v int) {
	es[e] += v
}
func (es *TerrainCmdVector) SetIfGt(e terraincmd.TerrainCmd, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es TerrainCmdVector) Get(e terraincmd.TerrainCmd) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es TerrainCmdVector) Iter(fn func(i terraincmd.TerrainCmd, v int) bool) bool {
	for i, v := range es {
		if fn(terraincmd.TerrainCmd(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es TerrainCmdVector) VectorAdd(arg TerrainCmdVector) TerrainCmdVector {
	var rtn TerrainCmdVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es TerrainCmdVector) VectorSub(arg TerrainCmdVector) TerrainCmdVector {
	var rtn TerrainCmdVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *TerrainCmdVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>TerrainCmd statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return terraincmd.TerrainCmd(i).String()
}

var IndexFn = template.FuncMap{
	"TerrainCmdIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{TerrainCmdIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
