// Code generated by "genenum.exe -typename=ReturnCode -packagename=returncode -basedir=enum -vectortype=int"

package returncode_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/returncode"
)

type ReturnCodeVector [returncode.ReturnCode_Count]int

func (es ReturnCodeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "ReturnCodeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			returncode.ReturnCode(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *ReturnCodeVector) Dec(e returncode.ReturnCode) {
	es[e] -= 1
}
func (es *ReturnCodeVector) Inc(e returncode.ReturnCode) {
	es[e] += 1
}
func (es *ReturnCodeVector) Add(e returncode.ReturnCode, v int) {
	es[e] += v
}
func (es *ReturnCodeVector) SetIfGt(e returncode.ReturnCode, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es ReturnCodeVector) Get(e returncode.ReturnCode) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es ReturnCodeVector) Iter(fn func(i returncode.ReturnCode, v int) bool) bool {
	for i, v := range es {
		if fn(returncode.ReturnCode(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es ReturnCodeVector) VectorAdd(arg ReturnCodeVector) ReturnCodeVector {
	var rtn ReturnCodeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es ReturnCodeVector) VectorSub(arg ReturnCodeVector) ReturnCodeVector {
	var rtn ReturnCodeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *ReturnCodeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>ReturnCode statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return returncode.ReturnCode(i).String()
}

var IndexFn = template.FuncMap{
	"ReturnCodeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{ReturnCodeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
