// Code generated by "genprotocol.exe -ver=4a12840e44ca35eea470dac2384a47d9415e454793d88901bc0b6da0c240e5cd -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_version

const ProtocolVersion = "4a12840e44ca35eea470dac2384a47d9415e454793d88901bc0b6da0c240e5cd"
