// Code generated by "genprotocol.exe -ver=2ac7ac69120d10cefa55d02b4dc610a33d5994ff1218aea5c255601ad7ab3a19 -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_version

const ProtocolVersion = "2ac7ac69120d10cefa55d02b4dc610a33d5994ff1218aea5c255601ad7ab3a19"
