// Code generated by "genprotocol.exe -ver=4ab5c823f1f31871cd0cef53b64b0920dee9d59673878aa337f0c3cb12b8a163 -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_version

const ProtocolVersion = "4ab5c823f1f31871cd0cef53b64b0920dee9d59673878aa337f0c3cb12b8a163"
