// Code generated by "genenum.exe -typename=FieldObjActType -packagename=fieldobjacttype -basedir=enum -vectortype=int"

package fieldobjacttype

import "fmt"

type FieldObjActType uint8

const (
	None FieldObjActType = iota //
	//
	//  move ao position
	PortalInOut     // portal in/out
	PortalIn        // portal oneway
	PortalOut       // portal out only
	PortalAutoIn    // portal auto in oneway
	RecycleCarryObj // recycle carryobj to money
	Teleport        // teleport somewhere
	//
	//  change ao attrib
	ForgetFloor    // forget current floor
	ForgetOneFloor // forget some floor you visited
	AlterFaction   // change faction randomly
	AllFaction     // rotate all faction
	//
	//  damage ao
	Bleeding // hp damage
	Chilly   // sp damage
	//
	//  affect condition
	Blind     // sight 0
	Invisible // other cannot see you
	Burden    // overload limit reduced
	Float     // float in air
	Greasy    // greasy body
	Drunken   // random direction
	Sleepy    // cannot act
	Contagion // make contagion other, die or heal randomly
	Slow      // act need turn doubled
	Haste     // act need turn halfed
	//
	//  make moving dangerobj
	RotateLineAttack // rotate line of dangerobj
	Mine             // explode on trigger

	FieldObjActType_Count int = iota
)

var _FieldObjActType2string = [FieldObjActType_Count][2]string{
	None:             {"None", ""},
	PortalInOut:      {"PortalInOut", "portal in/out"},
	PortalIn:         {"PortalIn", "portal oneway"},
	PortalOut:        {"PortalOut", "portal out only"},
	PortalAutoIn:     {"PortalAutoIn", "portal auto in oneway"},
	RecycleCarryObj:  {"RecycleCarryObj", "recycle carryobj to money"},
	Teleport:         {"Teleport", "teleport somewhere"},
	ForgetFloor:      {"ForgetFloor", "forget current floor"},
	ForgetOneFloor:   {"ForgetOneFloor", "forget some floor you visited"},
	AlterFaction:     {"AlterFaction", "change faction randomly"},
	AllFaction:       {"AllFaction", "rotate all faction"},
	Bleeding:         {"Bleeding", "hp damage"},
	Chilly:           {"Chilly", "sp damage"},
	Blind:            {"Blind", "sight 0"},
	Invisible:        {"Invisible", "other cannot see you"},
	Burden:           {"Burden", "overload limit reduced"},
	Float:            {"Float", "float in air"},
	Greasy:           {"Greasy", "greasy body"},
	Drunken:          {"Drunken", "random direction"},
	Sleepy:           {"Sleepy", "cannot act"},
	Contagion:        {"Contagion", "make contagion other, die or heal randomly"},
	Slow:             {"Slow", "act need turn doubled"},
	Haste:            {"Haste", "act need turn halfed"},
	RotateLineAttack: {"RotateLineAttack", "rotate line of dangerobj"},
	Mine:             {"Mine", "explode on trigger"},
}

func (e FieldObjActType) String() string {
	if e >= 0 && e < FieldObjActType(FieldObjActType_Count) {
		return _FieldObjActType2string[e][0]
	}
	return fmt.Sprintf("FieldObjActType%d", uint8(e))
}

func (e FieldObjActType) CommentString() string {
	if e >= 0 && e < FieldObjActType(FieldObjActType_Count) {
		return _FieldObjActType2string[e][1]
	}
	return ""
}

var _string2FieldObjActType = map[string]FieldObjActType{
	"None":             None,
	"PortalInOut":      PortalInOut,
	"PortalIn":         PortalIn,
	"PortalOut":        PortalOut,
	"PortalAutoIn":     PortalAutoIn,
	"RecycleCarryObj":  RecycleCarryObj,
	"Teleport":         Teleport,
	"ForgetFloor":      ForgetFloor,
	"ForgetOneFloor":   ForgetOneFloor,
	"AlterFaction":     AlterFaction,
	"AllFaction":       AllFaction,
	"Bleeding":         Bleeding,
	"Chilly":           Chilly,
	"Blind":            Blind,
	"Invisible":        Invisible,
	"Burden":           Burden,
	"Float":            Float,
	"Greasy":           Greasy,
	"Drunken":          Drunken,
	"Sleepy":           Sleepy,
	"Contagion":        Contagion,
	"Slow":             Slow,
	"Haste":            Haste,
	"RotateLineAttack": RotateLineAttack,
	"Mine":             Mine,
}

func String2FieldObjActType(s string) (FieldObjActType, bool) {
	v, b := _string2FieldObjActType[s]
	return v, b
}
