// Code generated by "genenum.exe -typename=ScrollType -packagename=scrolltype -basedir=enum -vectortype=int"

package scrolltype

import "fmt"

type ScrollType uint8

const (
	Empty    ScrollType = iota // empty scroll
	FloorMap                   // reveal all tile in current floor
	Teleport                   // teleport random in floor
	//
	FactionRnd  // change faction random
	FactionNext // change to next faction
	FactionBorn // change born faction
	//
	FactionBlack           // change faction to Black
	FactionMaroon          // change faction to Maroon
	FactionRed             // change faction to Red
	FactionGreen           // change faction to Green
	FactionOlive           // change faction to Olive
	FactionDarkOrange      // change faction to DarkOrange
	FactionLime            // change faction to Lime
	FactionChartreuse      // change faction to Chartreuse
	FactionYellow          // change faction to Yellow
	FactionNavy            // change faction to Navy
	FactionPurple          // change faction to Purple
	FactionDeepPink        // change faction to DeepPink
	FactionTeal            // change faction to Teal
	FactionSalmon          // change faction to Salmon
	FactionSpringGreen     // change faction to SpringGreen
	FactionLightGreen      // change faction to LightGreen
	FactionKhaki           // change faction to Khaki
	FactionBlue            // change faction to Blue
	FactionDarkViolet      // change faction to DarkViolet
	FactionMagenta         // change faction to Magenta
	FactionDodgerBlue      // change faction to DodgerBlue
	FactionMediumSlateBlue // change faction to MediumSlateBlue
	FactionViolet          // change faction to Violet
	FactionCyan            // change faction to Cyan
	FactionAquamarine      // change faction to Aquamarine
	FactionWhite           // change faction to White
	//
	BiasNeg     // change bias +/- to -/+
	BiasRotateR // rotate bias element right, RGB to BRG
	BiasRotateL // rotate bias element left, RGB to GBR

	ScrollType_Count int = iota
)

var _ScrollType2string = [ScrollType_Count][2]string{
	Empty:                  {"Empty", "empty scroll"},
	FloorMap:               {"FloorMap", "reveal all tile in current floor"},
	Teleport:               {"Teleport", "teleport random in floor"},
	FactionRnd:             {"FactionRnd", "change faction random"},
	FactionNext:            {"FactionNext", "change to next faction"},
	FactionBorn:            {"FactionBorn", "change born faction"},
	FactionBlack:           {"FactionBlack", "change faction to Black"},
	FactionMaroon:          {"FactionMaroon", "change faction to Maroon"},
	FactionRed:             {"FactionRed", "change faction to Red"},
	FactionGreen:           {"FactionGreen", "change faction to Green"},
	FactionOlive:           {"FactionOlive", "change faction to Olive"},
	FactionDarkOrange:      {"FactionDarkOrange", "change faction to DarkOrange"},
	FactionLime:            {"FactionLime", "change faction to Lime"},
	FactionChartreuse:      {"FactionChartreuse", "change faction to Chartreuse"},
	FactionYellow:          {"FactionYellow", "change faction to Yellow"},
	FactionNavy:            {"FactionNavy", "change faction to Navy"},
	FactionPurple:          {"FactionPurple", "change faction to Purple"},
	FactionDeepPink:        {"FactionDeepPink", "change faction to DeepPink"},
	FactionTeal:            {"FactionTeal", "change faction to Teal"},
	FactionSalmon:          {"FactionSalmon", "change faction to Salmon"},
	FactionSpringGreen:     {"FactionSpringGreen", "change faction to SpringGreen"},
	FactionLightGreen:      {"FactionLightGreen", "change faction to LightGreen"},
	FactionKhaki:           {"FactionKhaki", "change faction to Khaki"},
	FactionBlue:            {"FactionBlue", "change faction to Blue"},
	FactionDarkViolet:      {"FactionDarkViolet", "change faction to DarkViolet"},
	FactionMagenta:         {"FactionMagenta", "change faction to Magenta"},
	FactionDodgerBlue:      {"FactionDodgerBlue", "change faction to DodgerBlue"},
	FactionMediumSlateBlue: {"FactionMediumSlateBlue", "change faction to MediumSlateBlue"},
	FactionViolet:          {"FactionViolet", "change faction to Violet"},
	FactionCyan:            {"FactionCyan", "change faction to Cyan"},
	FactionAquamarine:      {"FactionAquamarine", "change faction to Aquamarine"},
	FactionWhite:           {"FactionWhite", "change faction to White"},
	BiasNeg:                {"BiasNeg", "change bias +/- to -/+"},
	BiasRotateR:            {"BiasRotateR", "rotate bias element right, RGB to BRG"},
	BiasRotateL:            {"BiasRotateL", "rotate bias element left, RGB to GBR"},
}

func (e ScrollType) String() string {
	if e >= 0 && e < ScrollType(ScrollType_Count) {
		return _ScrollType2string[e][0]
	}
	return fmt.Sprintf("ScrollType%d", uint8(e))
}

func (e ScrollType) CommentString() string {
	if e >= 0 && e < ScrollType(ScrollType_Count) {
		return _ScrollType2string[e][1]
	}
	return ""
}

var _string2ScrollType = map[string]ScrollType{
	"Empty":                  Empty,
	"FloorMap":               FloorMap,
	"Teleport":               Teleport,
	"FactionRnd":             FactionRnd,
	"FactionNext":            FactionNext,
	"FactionBorn":            FactionBorn,
	"FactionBlack":           FactionBlack,
	"FactionMaroon":          FactionMaroon,
	"FactionRed":             FactionRed,
	"FactionGreen":           FactionGreen,
	"FactionOlive":           FactionOlive,
	"FactionDarkOrange":      FactionDarkOrange,
	"FactionLime":            FactionLime,
	"FactionChartreuse":      FactionChartreuse,
	"FactionYellow":          FactionYellow,
	"FactionNavy":            FactionNavy,
	"FactionPurple":          FactionPurple,
	"FactionDeepPink":        FactionDeepPink,
	"FactionTeal":            FactionTeal,
	"FactionSalmon":          FactionSalmon,
	"FactionSpringGreen":     FactionSpringGreen,
	"FactionLightGreen":      FactionLightGreen,
	"FactionKhaki":           FactionKhaki,
	"FactionBlue":            FactionBlue,
	"FactionDarkViolet":      FactionDarkViolet,
	"FactionMagenta":         FactionMagenta,
	"FactionDodgerBlue":      FactionDodgerBlue,
	"FactionMediumSlateBlue": FactionMediumSlateBlue,
	"FactionViolet":          FactionViolet,
	"FactionCyan":            FactionCyan,
	"FactionAquamarine":      FactionAquamarine,
	"FactionWhite":           FactionWhite,
	"BiasNeg":                BiasNeg,
	"BiasRotateR":            BiasRotateR,
	"BiasRotateL":            BiasRotateL,
}

func String2ScrollType(s string) (ScrollType, bool) {
	v, b := _string2ScrollType[s]
	return v, b
}
