// Code generated by "genprotocol.exe -ver=4ab5c823f1f31871cd0cef53b64b0920dee9d59673878aa337f0c3cb12b8a163 -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	EnterFloor     NotiID = iota //
	LeaveFloor                   //
	Ageing                       //          // floor
	Death                        //
	ReadyToRebirth               //
	Rebirthed                    //
	VPObjList                    //       // in viewport, every turn
	VPTiles                      //         // in viewport, when viewport changed only
	FloorTiles                   //      // for rebuild known floor
	FieldObjList                 //    // for rebuild known floor
	FoundFieldObj                //   // hidden field obj
	ForgetFloor                  //
	ActivateTrap                 //

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count][2]string{
	EnterFloor:     {"EnterFloor", ""},
	LeaveFloor:     {"LeaveFloor", ""},
	Ageing:         {"Ageing", "         // floor"},
	Death:          {"Death", ""},
	ReadyToRebirth: {"ReadyToRebirth", ""},
	Rebirthed:      {"Rebirthed", ""},
	VPObjList:      {"VPObjList", "      // in viewport, every turn"},
	VPTiles:        {"VPTiles", "        // in viewport, when viewport changed only"},
	FloorTiles:     {"FloorTiles", "     // for rebuild known floor"},
	FieldObjList:   {"FieldObjList", "   // for rebuild known floor"},
	FoundFieldObj:  {"FoundFieldObj", "  // hidden field obj"},
	ForgetFloor:    {"ForgetFloor", ""},
	ActivateTrap:   {"ActivateTrap", ""},
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][0]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}
func (e NotiID) CommentString() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][1]
	}
	return ""
}

var _string2NotiID = map[string]NotiID{
	"EnterFloor":     EnterFloor,
	"LeaveFloor":     LeaveFloor,
	"Ageing":         Ageing,
	"Death":          Death,
	"ReadyToRebirth": ReadyToRebirth,
	"Rebirthed":      Rebirthed,
	"VPObjList":      VPObjList,
	"VPTiles":        VPTiles,
	"FloorTiles":     FloorTiles,
	"FieldObjList":   FieldObjList,
	"FoundFieldObj":  FoundFieldObj,
	"ForgetFloor":    ForgetFloor,
	"ActivateTrap":   ActivateTrap,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
