// Code generated by "genprotocol.exe -ver=311f4dbd137e36f36978fbd8d92db3e25cfad1a4fdf4e54ab2fa7905b077600d -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid        NotiID = iota // make empty packet error
	EnterTower                   //
	EnterFloor                   //
	LeaveFloor                   //
	LeaveTower                   //
	Ageing                       //          // floor
	Death                        //
	ReadyToRebirth               //
	Rebirthed                    //
	Broadcast                    //       // global chat broadcast from web admin
	VPObjList                    //       // in viewport, every turn
	VPTiles                      //         // in viewport, when viewport changed only
	FloorTiles                   //      // for rebuild known floor
	FieldObjList                 //    // for rebuild known floor
	FoundFieldObj                //   // hidden field obj
	ForgetFloor                  //
	ActivateTrap                 //

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count][2]string{
	Invalid:        {"Invalid", "make empty packet error"},
	EnterTower:     {"EnterTower", ""},
	EnterFloor:     {"EnterFloor", ""},
	LeaveFloor:     {"LeaveFloor", ""},
	LeaveTower:     {"LeaveTower", ""},
	Ageing:         {"Ageing", "         // floor"},
	Death:          {"Death", ""},
	ReadyToRebirth: {"ReadyToRebirth", ""},
	Rebirthed:      {"Rebirthed", ""},
	Broadcast:      {"Broadcast", "      // global chat broadcast from web admin"},
	VPObjList:      {"VPObjList", "      // in viewport, every turn"},
	VPTiles:        {"VPTiles", "        // in viewport, when viewport changed only"},
	FloorTiles:     {"FloorTiles", "     // for rebuild known floor"},
	FieldObjList:   {"FieldObjList", "   // for rebuild known floor"},
	FoundFieldObj:  {"FoundFieldObj", "  // hidden field obj"},
	ForgetFloor:    {"ForgetFloor", ""},
	ActivateTrap:   {"ActivateTrap", ""},
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][0]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}
func (e NotiID) CommentString() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][1]
	}
	return ""
}

var _string2NotiID = map[string]NotiID{
	"Invalid":        Invalid,
	"EnterTower":     EnterTower,
	"EnterFloor":     EnterFloor,
	"LeaveFloor":     LeaveFloor,
	"LeaveTower":     LeaveTower,
	"Ageing":         Ageing,
	"Death":          Death,
	"ReadyToRebirth": ReadyToRebirth,
	"Rebirthed":      Rebirthed,
	"Broadcast":      Broadcast,
	"VPObjList":      VPObjList,
	"VPTiles":        VPTiles,
	"FloorTiles":     FloorTiles,
	"FieldObjList":   FieldObjList,
	"FoundFieldObj":  FoundFieldObj,
	"ForgetFloor":    ForgetFloor,
	"ActivateTrap":   ActivateTrap,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
