// Code generated by "genenum.exe -typename=Tile -packagename=tile -basedir=enum -flagtype=uint16 -vectortype=int"

package tile_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/tile"
)

type TileVector [tile.Tile_Count]int

func (es TileVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "TileVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			tile.Tile(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *TileVector) Dec(e tile.Tile) {
	es[e] -= 1
}
func (es *TileVector) Inc(e tile.Tile) {
	es[e] += 1
}
func (es *TileVector) Add(e tile.Tile, v int) {
	es[e] += v
}
func (es *TileVector) SetIfGt(e tile.Tile, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es TileVector) Get(e tile.Tile) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es TileVector) Iter(fn func(i tile.Tile, v int) bool) bool {
	for i, v := range es {
		if fn(tile.Tile(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es TileVector) VectorAdd(arg TileVector) TileVector {
	var rtn TileVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es TileVector) VectorSub(arg TileVector) TileVector {
	var rtn TileVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *TileVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>Tile statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return tile.Tile(i).String()
}

var IndexFn = template.FuncMap{
	"TileIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{TileIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
