// Code generated by "genenum.exe -typename=EquipSlotType -packagename=equipslottype -basedir=enum -vectortype=int"

package equipslottype_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/equipslottype"
)

type EquipSlotTypeVector [equipslottype.EquipSlotType_Count]int

func (es EquipSlotTypeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "EquipSlotTypeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			equipslottype.EquipSlotType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *EquipSlotTypeVector) Dec(e equipslottype.EquipSlotType) {
	es[e] -= 1
}
func (es *EquipSlotTypeVector) Inc(e equipslottype.EquipSlotType) {
	es[e] += 1
}
func (es *EquipSlotTypeVector) Add(e equipslottype.EquipSlotType, v int) {
	es[e] += v
}
func (es *EquipSlotTypeVector) SetIfGt(e equipslottype.EquipSlotType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es EquipSlotTypeVector) Get(e equipslottype.EquipSlotType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es EquipSlotTypeVector) Iter(fn func(i equipslottype.EquipSlotType, v int) bool) bool {
	for i, v := range es {
		if fn(equipslottype.EquipSlotType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es EquipSlotTypeVector) VectorAdd(arg EquipSlotTypeVector) EquipSlotTypeVector {
	var rtn EquipSlotTypeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es EquipSlotTypeVector) VectorSub(arg EquipSlotTypeVector) EquipSlotTypeVector {
	var rtn EquipSlotTypeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *EquipSlotTypeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>EquipSlotType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return equipslottype.EquipSlotType(i).String()
}

var IndexFn = template.FuncMap{
	"EquipSlotTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{EquipSlotTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
