// Code generated by "genenum.exe -typename=FactionType -packagename=factiontype -basedir=enum -vectortype=int"

package factiontype

import "fmt"

type FactionType uint8

const (
	Black           FactionType = iota //
	Maroon                             //
	Red                                //
	Green                              //
	Olive                              //
	DarkOrange                         //
	Lime                               //
	Chartreuse                         //
	Yellow                             //
	Navy                               //
	Purple                             //
	DeepPink                           //
	Teal                               //
	Salmon                             //
	SpringGreen                        //
	LightGreen                         //
	Khaki                              //
	Blue                               //
	DarkViolet                         //
	Magenta                            //
	DodgerBlue                         //
	MediumSlateBlue                    //
	Violet                             //
	Cyan                               //
	Aquamarine                         //
	White                              //

	FactionType_Count int = iota
)

var _FactionType2string = [FactionType_Count][2]string{
	Black:           {"Black", ""},
	Maroon:          {"Maroon", ""},
	Red:             {"Red", ""},
	Green:           {"Green", ""},
	Olive:           {"Olive", ""},
	DarkOrange:      {"DarkOrange", ""},
	Lime:            {"Lime", ""},
	Chartreuse:      {"Chartreuse", ""},
	Yellow:          {"Yellow", ""},
	Navy:            {"Navy", ""},
	Purple:          {"Purple", ""},
	DeepPink:        {"DeepPink", ""},
	Teal:            {"Teal", ""},
	Salmon:          {"Salmon", ""},
	SpringGreen:     {"SpringGreen", ""},
	LightGreen:      {"LightGreen", ""},
	Khaki:           {"Khaki", ""},
	Blue:            {"Blue", ""},
	DarkViolet:      {"DarkViolet", ""},
	Magenta:         {"Magenta", ""},
	DodgerBlue:      {"DodgerBlue", ""},
	MediumSlateBlue: {"MediumSlateBlue", ""},
	Violet:          {"Violet", ""},
	Cyan:            {"Cyan", ""},
	Aquamarine:      {"Aquamarine", ""},
	White:           {"White", ""},
}

func (e FactionType) String() string {
	if e >= 0 && e < FactionType(FactionType_Count) {
		return _FactionType2string[e][0]
	}
	return fmt.Sprintf("FactionType%d", uint8(e))
}

func (e FactionType) CommentString() string {
	if e >= 0 && e < FactionType(FactionType_Count) {
		return _FactionType2string[e][1]
	}
	return ""
}

var _string2FactionType = map[string]FactionType{
	"Black":           Black,
	"Maroon":          Maroon,
	"Red":             Red,
	"Green":           Green,
	"Olive":           Olive,
	"DarkOrange":      DarkOrange,
	"Lime":            Lime,
	"Chartreuse":      Chartreuse,
	"Yellow":          Yellow,
	"Navy":            Navy,
	"Purple":          Purple,
	"DeepPink":        DeepPink,
	"Teal":            Teal,
	"Salmon":          Salmon,
	"SpringGreen":     SpringGreen,
	"LightGreen":      LightGreen,
	"Khaki":           Khaki,
	"Blue":            Blue,
	"DarkViolet":      DarkViolet,
	"Magenta":         Magenta,
	"DodgerBlue":      DodgerBlue,
	"MediumSlateBlue": MediumSlateBlue,
	"Violet":          Violet,
	"Cyan":            Cyan,
	"Aquamarine":      Aquamarine,
	"White":           White,
}

func String2FactionType(s string) (FactionType, bool) {
	v, b := _string2FactionType[s]
	return v, b
}
