// Code generated by "genenum.exe -typename=AIPlan -packagename=aiplan -basedir=enum -vectortype=int"

package aiplan

import "fmt"

type AIPlan uint8

const (
	None           AIPlan = iota //
	Chat                         //
	StrollAround                 //
	Move2Dest                    //
	Revenge                      //
	UsePortal                    //
	MoveToRecycler               //
	RechargeSafe                 //
	RechargeCan                  //
	PickupCarryObj               //
	Equip                        //
	UsePotion                    //
	Attack                       //
	MoveStraight3                //
	MoveStraight5                //

	AIPlan_Count int = iota
)

var _AIPlan2string = [AIPlan_Count][2]string{
	None:           {"None", ""},
	Chat:           {"Chat", ""},
	StrollAround:   {"StrollAround", ""},
	Move2Dest:      {"Move2Dest", ""},
	Revenge:        {"Revenge", ""},
	UsePortal:      {"UsePortal", ""},
	MoveToRecycler: {"MoveToRecycler", ""},
	RechargeSafe:   {"RechargeSafe", ""},
	RechargeCan:    {"RechargeCan", ""},
	PickupCarryObj: {"PickupCarryObj", ""},
	Equip:          {"Equip", ""},
	UsePotion:      {"UsePotion", ""},
	Attack:         {"Attack", ""},
	MoveStraight3:  {"MoveStraight3", ""},
	MoveStraight5:  {"MoveStraight5", ""},
}

func (e AIPlan) String() string {
	if e >= 0 && e < AIPlan(AIPlan_Count) {
		return _AIPlan2string[e][0]
	}
	return fmt.Sprintf("AIPlan%d", uint8(e))
}

func (e AIPlan) CommentString() string {
	if e >= 0 && e < AIPlan(AIPlan_Count) {
		return _AIPlan2string[e][1]
	}
	return ""
}

var _string2AIPlan = map[string]AIPlan{
	"None":           None,
	"Chat":           Chat,
	"StrollAround":   StrollAround,
	"Move2Dest":      Move2Dest,
	"Revenge":        Revenge,
	"UsePortal":      UsePortal,
	"MoveToRecycler": MoveToRecycler,
	"RechargeSafe":   RechargeSafe,
	"RechargeCan":    RechargeCan,
	"PickupCarryObj": PickupCarryObj,
	"Equip":          Equip,
	"UsePotion":      UsePotion,
	"Attack":         Attack,
	"MoveStraight3":  MoveStraight3,
	"MoveStraight5":  MoveStraight5,
}

func String2AIPlan(s string) (AIPlan, bool) {
	v, b := _string2AIPlan[s]
	return v, b
}
