// Code generated by "genenum.exe -typename=DangerType -packagename=dangertype -basedir=enum -vectortype=int"

package dangertype_vector_int

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/dangertype"
)

type DangerTypeVector_int [dangertype.DangerType_Count]int

func (es DangerTypeVector_int) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "DangerTypeVector_int[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			dangertype.DangerType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *DangerTypeVector_int) Dec(e dangertype.DangerType) {
	es[e] -= 1
}
func (es *DangerTypeVector_int) Inc(e dangertype.DangerType) {
	es[e] += 1
}
func (es *DangerTypeVector_int) Add(e dangertype.DangerType, v int) {
	es[e] += v
}
func (es *DangerTypeVector_int) SetIfGt(e dangertype.DangerType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es DangerTypeVector_int) Get(e dangertype.DangerType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es DangerTypeVector_int) Iter(fn func(i dangertype.DangerType, v int) bool) bool {
	for i, v := range es {
		if fn(dangertype.DangerType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es DangerTypeVector_int) VectorAdd(arg DangerTypeVector_int) DangerTypeVector_int {
	var rtn DangerTypeVector_int
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es DangerTypeVector_int) VectorSub(arg DangerTypeVector_int) DangerTypeVector_int {
	var rtn DangerTypeVector_int
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *DangerTypeVector_int) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>DangerType Vector int</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return dangertype.DangerType(i).String()
}

var IndexFn = template.FuncMap{
	"DangerTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{DangerTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
