// Code generated by "genprotocol.exe -ver=4ab5c823f1f31871cd0cef53b64b0920dee9d59673878aa337f0c3cb12b8a163 -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_const

/*  copy to no _gen file, and edit it
const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xffff

	// ServerAPICallTimeOutDur api call watchdog timer, 0 : no api timeout
	ServerAPICallTimeOutDur = time.Second * 2
)
*/
