// Code generated by "genprotocol.exe -ver=311f4dbd137e36f36978fbd8d92db3e25cfad1a4fdf4e54ab2fa7905b077600d -basedir=protocol_c2t -prefix=c2t -statstype=int"

package c2t_const

/*  copy to no _gen file, and edit it
const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xffff

	// ServerAPICallTimeOutDur api call watchdog timer, 0 : no api timeout
	ServerAPICallTimeOutDur = time.Second * 2
)
*/
