package eventenum

import (
	"github.com/kasworld/goguelike-single/lib/engine/dispatcheri"
)

// OnExit is the event generated by Application when the user
// tries to close the window (desktop) or the Exit() method is called.
const OnExit = dispatcheri.EventName("app.OnExit")

// Node events.
const (
	// Dispatched when a descendent is added or removed
	OnDescendant = dispatcheri.EventName("node.OnDescendant")
)

const OnWindowClose = dispatcheri.EventName("gui.OnWindowClose")

// Window event names. See availability per platform below ("x" indicates available).
const ( //                             Desktop | Browser |
	OnWindowPos  = dispatcheri.EventName("w.OnWindowPos")  //    x    |         |
	OnWindowSize = dispatcheri.EventName("w.OnWindowSize") //    x    |         |
	OnKeyUp      = dispatcheri.EventName("w.OnKeyUp")      //    x    |    x    |
	OnKeyDown    = dispatcheri.EventName("w.OnKeyDown")    //    x    |    x    |
	OnKeyRepeat  = dispatcheri.EventName("w.OnKeyRepeat")  //    x    |         |
	OnChar       = dispatcheri.EventName("w.OnChar")       //    x    |    x    |
	OnCursor     = dispatcheri.EventName("w.OnCursor")     //    x    |    x    |
	OnMouseUp    = dispatcheri.EventName("w.OnMouseUp")    //    x    |    x    |
	OnMouseDown  = dispatcheri.EventName("w.OnMouseDown")  //    x    |    x    |
	OnScroll     = dispatcheri.EventName("w.OnScroll")     //    x    |    x    |
)

// Core events sent by the GUI manager.
// The target panel is the panel immediately under the mouse cursor.
const (

	// Events sent to all panels except the ancestors of the target panel
	OnMouseDownOut = dispatcheri.EventName("gui.OnMouseDownOut") // Any mouse button is pressed
	OnMouseUpOut   = dispatcheri.EventName("gui.OnMouseUpOut")   // Any mouse button is released

	// Event sent to new target panel and all of its ancestors up to
	// (not including) the common ancestor of the new and old targets
	// Cursor entered the panel or a descendant
	OnCursorEnter = dispatcheri.EventName("gui.OnCursorEnter")
	// Event sent to old target panel and all of its ancestors up to
	// (not including) the common ancestor of the new and old targets
	// Cursor left the panel or a descendant
	OnCursorLeave = dispatcheri.EventName("gui.OnCursorLeave")

	// Event sent to the new key-focused DispatcherI,
	// specified on a call to gui.Manager().SetKeyFocus(dispatcheri.DispatcherI)
	// All keyboard events will be exclusively sent to the receiving DispatcherI
	OnFocus = dispatcheri.EventName("gui.OnFocus")
	// Event sent to the previous key-focused DispatcherI when another panel is key-focused
	// Keyboard events will stop being sent to the receiving DispatcherI
	OnFocusLost = dispatcheri.EventName("gui.OnFocusLost")
)

const (
	// Panel size changed (no parameters)
	OnResize = dispatcheri.EventName("gui.OnResize")
	// Panel enabled/disabled (no parameters)
	OnEnable = dispatcheri.EventName("gui.OnEnable")
	// Widget clicked by mouse left button or via key press
	OnClick = dispatcheri.EventName("gui.OnClick")
	// Value was changed. Emitted by List, DropDownList, CheckBox and Edit
	OnChange = dispatcheri.EventName("gui.OnChange")
	// Radio button within a group changed state
	OnRadioGroup = dispatcheri.EventName("gui.OnRadioGroup")
)

const (
	// OnTableClick is the event generated when the table is right or left clicked
	// Parameter is TableClickEvent
	OnTableClick = dispatcheri.EventName("onTableClick")
	// OnTableRowCount is the event generated when the table row count changes (no parameters)
	OnTableRowCount = dispatcheri.EventName("onTableRowCount")
)

// Events
const (
	// Dispatched after a body has gone in to the sleepy state.
	SleepyEvent = dispatcheri.EventName("physics.SleepyEvent")
	// Dispatched after a body has fallen asleep.
	SleepEvent = dispatcheri.EventName("physics.SleepEvent")
	// Dispatched after a sleeping body has woken up.
	WakeUpEvent = dispatcheri.EventName("physics.WakeUpEvent")
	// Dispatched after two bodies collide.
	// This event is dispatched on each of the two bodies involved in the collision.
	CollideEvent = dispatcheri.EventName("physics.CollideEvent")
)

const (
	BeginContactEvent = dispatcheri.EventName("physics.BeginContactEvent")
	EndContactEvent   = dispatcheri.EventName("physics.EndContactEvent")
	CollisionEv       = dispatcheri.EventName("physics.Collision")
)

// OnListItemResize is the identifier of the event dispatched when a ListItem's child panel is resized
const OnListItemResize = "gui.OnListItemResize"
