// Code generated by "genenum.exe -typename=ActiveObjType -packagename=aotype -basedir=enum -vectortype=int"

package aotype_vector_int

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/goguelike-single/enum/aotype"
)

type ActiveObjTypeVector_int [aotype.ActiveObjType_Count]int

func (es ActiveObjTypeVector_int) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "ActiveObjTypeVector_int[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			aotype.ActiveObjType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *ActiveObjTypeVector_int) Dec(e aotype.ActiveObjType) {
	es[e] -= 1
}
func (es *ActiveObjTypeVector_int) Inc(e aotype.ActiveObjType) {
	es[e] += 1
}
func (es *ActiveObjTypeVector_int) Add(e aotype.ActiveObjType, v int) {
	es[e] += v
}
func (es *ActiveObjTypeVector_int) SetIfGt(e aotype.ActiveObjType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es ActiveObjTypeVector_int) Get(e aotype.ActiveObjType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es ActiveObjTypeVector_int) Iter(fn func(i aotype.ActiveObjType, v int) bool) bool {
	for i, v := range es {
		if fn(aotype.ActiveObjType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es ActiveObjTypeVector_int) VectorAdd(arg ActiveObjTypeVector_int) ActiveObjTypeVector_int {
	var rtn ActiveObjTypeVector_int
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es ActiveObjTypeVector_int) VectorSub(arg ActiveObjTypeVector_int) ActiveObjTypeVector_int {
	var rtn ActiveObjTypeVector_int
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *ActiveObjTypeVector_int) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>ActiveObjType Vector int</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return aotype.ActiveObjType(i).String()
}

var IndexFn = template.FuncMap{
	"ActiveObjTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{ActiveObjTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
